project_name: momo
builds:
  - id: momo
    main: ./cmd
    binary: momo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X 'momo/internal/version.Version={{.Tag}}'"
    mod_timestamp: "2023-01-01T00:00:00Z" # reproducible timestamp
archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
      - sbom-{{ .ProjectName }}.cyclonedx.json
      - ./cmd/{{ .ProjectName }}

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

release:
  github:
    owner: Bhagattji
    name: momo

signs:
  - artifacts: true
    args:
      - --detach-sign
    cmd: gpg

dockers: []

sbom:
  mode: file
  file: sbom-cyclonedx.json
  formats:
    - cyclonedx

# produce deb/rpm packages via nfpm
nfpms:
  - id: linux-deb
    packager: deb
    format: "deb"
    name: momo
    version: "{{ .Version }}"
    maintainer: "Momo Maintainers <dev@example.com>"
    description: "Momo CLI"
    files:
      - src: ./momo
        dst: /usr/local/bin/momo
  - id: linux-rpm
    packager: rpm
    format: "rpm"
    name: momo
    version: "{{ .Version }}"
    maintainer: "Momo Maintainers <dev@example.com>"
    description: "Momo CLI"
    files:
      - src: ./momo
        dst: /usr/local/bin/momo

changelog:
  use: simple
  body_template: "{{ range .Commits }}- {{ .Message | truncate 80 }}\n{{ end }}"
